# Generated by Django 5.0 on 2023-12-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedetail",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("customer_name", "date")},
        ),
    ]
