# Generated by Django 5.0 on 2023-12-31 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_alter_invoicedetail_quantity_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together=set(),
        ),
    ]
