# Generated by Django 5.0 on 2023-12-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0003_alter_invoice_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedetail",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
